remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-redirect-from

title: stutopp.net
description: Stu Topp is an Operations Research/Systems Analyst and US Army Veteran.
