remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-redirect-from

title: Stu Topp
description: professional cat herder and occasional ORSA, systems engineer, and offsec engineer
